# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        # Combine all images of last week
        patterns: ["*"]
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: "-"
    groups:
      major:
        update-types: ["major"]
      minor:
        update-types: ["minor"]
      patch:
        update-types: ["patch"]
    reviewers:
      - "AButler"
