name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore
        run: npm ci

      - name: Build
        run: npm run build

      - name: Check contributors
        run: npx all-contributors check
